import {Reactor} from '@reactor-team/js-sdk';
import {MODEL} from './prompts.js';
import {CAMERA} from './newsworthy-events.js';
export async function api(path,data={},keepalive=false){const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data),keepalive,...(!keepalive?{signal:AbortSignal.timeout(45000)}:{})});const v=await r.json();if(!r.ok)throw Object.assign(new Error(v.error||`Request failed (${r.status})`),{queue:v.queue});return v;}
const unwrap=r=>r?.data?{...r.data,type:r.type}:r||{};
const SESSION_KEY='newsworthy-reactor-session-v1';
function rememberSession(sessionId,jwt){sessionStorage.setItem(SESSION_KEY,JSON.stringify({sessionId,jwt}));}
function forgetSession(sessionId){try{const saved=JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null');if(!sessionId||saved?.sessionId===sessionId)sessionStorage.removeItem(SESSION_KEY);}catch{sessionStorage.removeItem(SESSION_KEY);}}
async function cleanupRememberedSession(){let saved;try{saved=JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null');}catch{forgetSession();return;}if(!saved?.sessionId||!saved?.jwt){forgetSession();return;}try{await api('cleanup',saved);}catch{}finally{forgetSession(saved.sessionId);}}
// Cloudflare Turnstile bot check, only where /api/status names a site key (production). Most players never see it.
let turnstileScript;
async function botCheck(){const sitekey=await fetch('/api/status').then(r=>r.json()).then(v=>v.turnstile).catch(()=>null);if(!sitekey)return undefined;turnstileScript??=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';s.async=true;s.onload=resolve;s.onerror=()=>{turnstileScript=null;reject(new Error('Couldn’t load the bot check. Check your connection and try again.'));};document.head.append(s);});await turnstileScript;const box=document.createElement('div');box.style.cssText='position:fixed;left:50%;bottom:24px;transform:translateX(-50%);z-index:1000';document.body.append(box);let id;try{return await new Promise((resolve,reject)=>{id=window.turnstile.render(box,{sitekey,appearance:'interaction-only',callback:resolve,'error-callback':()=>reject(new Error('The bot check didn’t go through. Try again.')),'timeout-callback':()=>reject(new Error('The bot check timed out. Try again.'))});});}finally{if(id!==undefined)window.turnstile.remove(id);box.remove();}}
export class LiveCity{
 constructor(video,status,failure){this.video=video;this.status=status;this.failure=failure;this.closed=false;this.chain=Promise.resolve();this.state={};this.conditions=0;this.log={id:'newsworthy-'+Date.now(),model:MODEL,reference:'news-judge/busy-opening-ufo-v4.png',created:new Date().toISOString(),events:[],prompts:[]};}
 record(type,data={}){this.log.events.push({t:Date.now(),type,...data});void api('save',this.log).catch(()=>{});}
 async wait(fn,ms=30000){const end=Date.now()+ms;while(!fn()){if(this.closed)throw new Error('Session stopped');if(Date.now()>end)throw new Error('The live city took too long to respond. Please try again.');await new Promise(r=>setTimeout(r,100));}}
 command(name,data={}){const queued=Date.now();const task=this.chain.then(async()=>{const sent=Date.now();this.record('command_sent',{command:name,queueMs:sent-queued});if(this.closed)throw new Error('Session stopped');const r=unwrap(await this.client.sendCommand(name,data));if(r.type==='command_error')throw new Error(r.reason||name+' rejected');this.record('command_ack',{command:name,ackMs:Date.now()-sent,...(name==='set_prompt'?{prompt:data.prompt}:{})});return r;});this.chain=task.catch(()=>{});return task;}
 // All cameras busy: the server puts the player in line. Check in with the ticket until it's their turn.
 async turn(first){let e;try{return await first;}catch(x){e=x;}while(e.queue&&!this.closed){this.waiting?.(e.queue);await new Promise(r=>setTimeout(r,3000));if(this.closed)break;try{const v=await api('token',{ticket:e.queue.ticket});this.waiting?.(null);return v;}catch(x){e=x;}}this.waiting?.(null);throw this.closed?new Error('Session stopped'):e;}
 async start(){this.status('Checking the previous live session…');await cleanupRememberedSession();this.status('Opening a live session…');({jwt:this.jwt}=await this.turn(api('token',{turnstile:await botCheck()})));if(this.closed)return;const client=this.client=new Reactor({modelName:MODEL,readyTimeoutMs:120000,controlRequestTimeoutMs:30000,maxSessionAttempts:1,logLevel:'error',modelTracks:[{name:'main_video',kind:'video',direction:'recvonly'},{name:'main_audio',kind:'audio',direction:'recvonly'}]});const stream=this.stream=new MediaStream();this.video.srcObject=stream;void this.video.play().catch(()=>{});
 client.on('sessionIdChanged',id=>{if(!id)return;this.id=id;rememberSession(id,this.jwt);void api(this.closed?'cleanup':'session',{sessionId:id,jwt:this.jwt}).then(()=>{if(this.closed)forgetSession(id);}).catch(e=>this.failure(e));});
 client.on('statusChanged',s=>{if(this.closed)return;if(s==='waiting'&&!this.live)this.status('Warming up the city…');if(s==='disconnected'&&this.live)this.failure(new Error('The live connection closed. End this round and try again.'));});
 client.on('message',raw=>{const r=unwrap(raw);if(r.type==='state')Object.assign(this.state,r);if(r.type==='conditions_ready')this.conditions++;if(r.type==='command_error')this.record('model_error',{reason:r.reason});});
 client.on('trackReceived',(name,track)=>{if(this.closed||!name.startsWith('main_'))return;const old=stream.getTracks().find(t=>t.kind===track.kind);if(old)stream.removeTrack(old);stream.addTrack(track);void this.video.play().catch(()=>{});});
 await client.connect(this.jwt);if(this.closed)return;this.status('Preparing the opening scene…');const blob=await fetch('/news-judge/busy-opening-ufo-v4.png').then(r=>r.blob());const image=await client.uploadFile(new File([blob],'busy-opening-ufo-v4.png',{type:'image/png'}));await this.command('set_image',{image});await this.wait(()=>this.state.has_image===true);const resolution=this.state.available_resolutions?.find(r=>r==='1080p');if(resolution)await this.command('set_resolution',{resolution});const before=this.conditions;await this.command('set_prompt',{prompt:'Three incidents are already happening across the streets in daylight. Large orange flames burn on a crashed car beside a bus near the center-left of the intersection. Smoke rises. A giant yellow rubber duck blocks another intersection as cars drive around it. A large silver alien flying saucer hovers above the road. A narrow blue beam shines straight down from the saucer onto the street. A small circle of blue light illuminates one lane below. All three incidents remain visible in the wide view. '+CAMERA,passthrough:false});await this.wait(()=>this.conditions>before);await this.command('start');this.status('Waiting for live video…');let arrived=false;this.frame=this.video.requestVideoFrameCallback(()=>{arrived=true;});await this.wait(()=>arrived,120000);this.live=true;this.record('first_video_frame');}
 async close(){if(this.closed)return;this.closed=true;if(this.frame)this.video.cancelVideoFrameCallback(this.frame);try{if(this.id){await api('cleanup',{sessionId:this.id,jwt:this.jwt});forgetSession(this.id);}}finally{await this.client?.disconnect().catch(()=>{});this.stream?.getTracks().forEach(t=>t.stop());this.record('closed');}}
 unload(){this.closed=true;if(this.id){void api('cleanup',{sessionId:this.id,jwt:this.jwt},true).then(()=>forgetSession(this.id)).catch(()=>{});void this.client?.disconnect().catch(()=>{});}}
}
