import {installDialogMotion,shutter,revealRecap} from './newsworthy-motion.js';
import {addEventHistory,resetEventHistory} from './newsworthy-event-history.js';
import {dollars,tintPhoto,photoTitle,countMoney,detailsFor,reviewEye} from './newsworthy-photo-ui.js';
import {renderGallery} from './newsworthy-recap.js';
import {createFrontPage,createPhotoPackage} from './newsworthy-keepsake.js';
import {LiveCity,api} from './newsworthy-stream.js';
import {EVENTS,EVENT_WINDOW_MS} from './newsworthy-events.js';
import {cropRect} from './newsworthy-crop.js';
import {eventIcon} from './newsworthy-icons.js';
import {context,setSound,shutterSound,moneySound,startLoadingSound,stopLoadingSound} from './newsworthy-sounds.js';
import {playIntro,VIEWFINDER_BEATS} from './newsworthy-intro.js';
const $=s=>document.querySelector(s),video=$('#feed'),empty=$('#photos').innerHTML;
const LIVE_VOLUME=.5,DIALOG_VOLUME=.08,VOLUME_FADE_MS=400;
let volumeFade;
function fadeFeedVolume(target,duration=VOLUME_FADE_MS){cancelAnimationFrame(volumeFade);const from=video.volume;if(!duration){video.volume=target;return;}const started=performance.now();const tick=now=>{const progress=Math.min(1,(now-started)/duration),eased=1-Math.pow(1-progress,3);video.volume=from+(target-from)*eased;if(progress<1)volumeFade=requestAnimationFrame(tick);};volumeFade=requestAnimationFrame(tick);}
fadeFeedVolume(LIVE_VOLUME,0);
let city,roundId,phase='idle',shots=[],money=0,deadline=0,pausedAt=0,cooling=0,sending=false,sound=true,epoch=0,processing=false,queue=[],ending=false,photoReadyAt=0,currentShot=null,retryTimer=0,customSent=false;
let intro,lastIncident=null,aimX=.5,aimY=.45,eventTurn=0,playing=false;
function renderOptions(){const box=$('#event-options');box.replaceChildren();for(const [index,event] of EVENTS.entries()){const button=document.createElement('button');button.dataset.event=event.id;const code=eventIcon(event.id,event.code);const number=document.createElement('span');number.className='event-number';number.textContent=String(index+1).padStart(2,'0');const label=document.createElement('span');label.className='event-label';label.textContent=event.label;button.append(code,number,label);button.onclick=()=>void send(event.prompt,event.label);box.append(button);}}
function refreshEvents(){if(playing&&!sending&&Date.now()>=cooling){playing=false;eventTurn++;renderOptions();}$('#event-options').hidden=false;}
const broadcast=$('.picture-stage');
function aim(){const r=broadcast.getBoundingClientRect();const crop=cropRect(video.videoWidth||1280,video.videoHeight||720,r.width,r.height,aimX,aimY,.48,'contain');Object.assign($('#aim').style,{left:crop.left+'px',top:crop.top+'px',width:crop.width+'px',height:crop.height+'px'});return crop;}
broadcast.addEventListener('pointermove',e=>{if(e.target.closest('button,dialog'))return;const r=broadcast.getBoundingClientRect();aimX=(e.clientX-r.left)/r.width;aimY=(e.clientY-r.top)/r.height;aim();});
broadcast.addEventListener('click',e=>{if(e.target.closest('button,dialog,#connection,.on-air,.stats'))return;const r=broadcast.getBoundingClientRect();aimX=(e.clientX-r.left)/r.width;aimY=(e.clientY-r.top)/r.height;aim();capture();});
new ResizeObserver(()=>aim()).observe(broadcast);video.addEventListener('loadedmetadata',aim);video.addEventListener('resize',aim);
function status(t){$('#notice').textContent=t;$('#notice').classList.toggle('incoming',t.startsWith('Incoming:'));}
function total(){['money','final-total'].forEach(id=>$('#'+id).textContent='$'+money.toLocaleString());}
function left(){return deadline?Math.max(0,Math.ceil((deadline-Date.now())/1000)):120;}
function controls(){const active=phase==='live'&&!ending&&!$('#sale').open&&!$('#photo-detail').open;const photoWait=Math.max(0,(photoReadyAt-Date.now())/1000);$('#aim .shoot-hint').hidden=shots.length>0;$('#aim').classList.toggle('low-shots',shots.length>=9);$('#aim').classList.toggle('cooling',photoWait>0);refreshEvents();document.querySelectorAll('[data-event]').forEach(b=>{b.disabled=!active||sending||playing;});const wait=Math.max(0,Math.ceil((cooling-Date.now())/1000));$('.event-desk').classList.toggle('events-locked',playing);$('#event-timer').classList.toggle('ready',!playing);$('#event-timer').style.setProperty('--cooldown-fill',(sending?1:Math.max(0,Math.min(1,(cooling-Date.now())/EVENT_WINDOW_MS)))*100+'%');$('#event-timer-name').textContent=!playing?'Ready — pick one':(sending?'Sending: ':'Sent: ')+lastIncident.label;$('#event-timer-left').textContent=playing&&!sending?`Next in ${wait}s`:'';$('#custom button').disabled=!active||sending||playing;$('#idea').disabled=!active||playing;$('#remaining').textContent=12-shots.length;$('#shots-label').textContent=shots.length===11?' SHOT LEFT':' SHOTS LEFT';$('#count').textContent=shots.length+' / 12';const s=left();$('#clock').textContent=Math.floor(s/60)+':'+String(s%60).padStart(2,'0');$('#restart').disabled=phase==='starting'||phase==='closing';}
async function start(){if(['starting','closing','live'].includes(phase))return;clearTimeout(retryTimer);retryTimer=0;const run=++epoch;phase='starting';fadeFeedVolume(LIVE_VOLUME,0);$('#restart').hidden=true;ending=false;shots=[];currentShot=null;$('#sale').close();money=0;photoReadyAt=0;customSent=false;deadline=0;pausedAt=0;queue=[];processing=false;cooling=0;sending=false;roundId=null;eventTurn=0;playing=false;renderOptions();lastIncident=null;resetEventHistory();total();$('#photos').innerHTML=empty;$('#welcome').close();$('#result').close();intro?.stop();const opening=intro=playIntro($('#connection'),{beats:VIEWFINDER_BEATS});$('#connection-note').hidden=true;$('#retry-connect').hidden=true;$('#release').hidden=true;$('#opening-scene').hidden=false;video.muted=!sound;void video.play().catch(()=>{});startLoadingSound();controls();try{const instance=city=new LiveCity(video,status,e=>{if(run!==epoch)return;status(e.message);if(phase==='live')void end();});instance.waiting=q=>{if(run!==epoch)return;$('#connection-note').hidden=!q;if(!q)return;const n=q.position,place=n===1?'You’re next in line.':`You’re ${n}${n%100>10&&n%100<14?'th':['th','st','nd','rd'][n%10]||'th'} in line.`;status(place+' All cameras are busy.');$('#connection-note').textContent=place+' Your round starts on its own when a camera frees up.';$('#intro-sub').hidden=true;};const [round]=await Promise.all([instance.start().then(()=>instance.jwt&&api('news-round',{jwt:instance.jwt})),opening.ready]);if(run!==epoch||instance.closed)return;roundId=round.roundId;stopLoadingSound();$('#opening-scene').hidden=true;opening.live();phase='live';deadline=Date.now()+120000;status('You’re live. Find a story and get the shot.');controls();}catch(e){if(run!==epoch)return;opening.stop();stopLoadingSound();console.warn('Live start failed',e);await city?.close().catch(()=>{});phase='error';const message=String(e?.message||e),busy=/quota_exceeded|concurrent_sessions_per_model/.test(message);status(busy?'Previous live session is still closing. Retrying automatically…':message);$('#connection-title').textContent=busy?'Almost there.':'Couldn’t reach the city.';$('#connection-note').textContent=busy?'Trying again in 10 seconds.':'Your round hasn’t started. Try again in a moment.';$('#connection-note').hidden=false;$('#retry-connect').hidden=false;$('#release').hidden=!message.includes('session is still open');if(busy)retryTimer=setTimeout(()=>{retryTimer=0;if(run===epoch&&phase==='error')void start();},10000);controls();}}
async function send(prompt,label,custom=false){if(phase!=='live'||ending||sending||playing||$('#sale').open)return;sending=true;playing=true;lastIncident={label,clicked:Date.now(),activeElapsed:0};city.record('incident_clicked',{label});controls();status('Sending: '+label);try{await city.command('set_prompt',{prompt,passthrough:false});lastIncident.accepted=Date.now();if(custom)customSent=true;addEventHistory(label,120-left());const incoming='Incoming: '+label;status(incoming);setTimeout(()=>{if($('#notice').textContent===incoming)status('Sent: '+label);},5000);}catch(e){status('Prompt not confirmed: '+e.message);}finally{sending=false;cooling=Date.now()+EVENT_WINDOW_MS;controls();}}
$('#idea').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('#custom').requestSubmit();}});
$('#custom').onsubmit=e=>{e.preventDefault();const text=$('#idea').value.trim();if(text&&phase==='live'&&!ending&&!sending&&!playing&&!$('#sale').open){void send(text,text,true);$('#idea').value='';}};
async function capture(){if(phase!=='live'||ending||shots.length>=12||($('#sale').open||$('#photo-detail').open)||!left()||video.readyState<2||Date.now()<photoReadyAt)return;const runEpoch=epoch;const c=document.createElement('canvas');const crop=aim();c.width=Math.min(960,Math.round(crop.sw));c.height=Math.round(c.width*3/4);c.getContext('2d').drawImage(video,crop.sx,crop.sy,crop.sw,crop.sh,0,0,c.width,c.height);const scaled=w=>{const s=document.createElement('canvas');s.width=Math.min(w,c.width);s.height=Math.round(s.width*3/4);s.getContext('2d').drawImage(c,0,0,s.width,s.height);return s.toDataURL('image/jpeg',.82);};const shot={id:'shot-'+(shots.length+1),image:c.toDataURL('image/jpeg',.82),judged:scaled(640),thumb:scaled(384),custom:customSent,state:'pending'};shots.push(shot);photoReadyAt=Date.now()+2000;city.record('photo_captured',{photoId:shot.id});shutterSound();const shutterDone=shutter($('#flash'));$('#photos .empty')?.remove();const card=document.createElement('article');card.className='photo reviewing';shot.card=card;const image=new Image();image.src=shot.image;image.alt='Your photo '+shots.length;shot.meta=document.createElement('div');shot.meta.className='photo-meta';shot.title=document.createElement('h3');shot.title.textContent='Reviewing…';shot.retry=document.createElement('button');shot.retry.className='retry-photo';shot.retry.textContent='RETRY PHOTO';shot.retry.hidden=true;shot.retry.onclick=()=>retryShot(shot);const photoButton=document.createElement('button');photoButton.className='roll-photo-button';photoButton.setAttribute('aria-label','View photo '+shots.length);photoButton.onclick=()=>{if(shot.result)inspectPhoto(shot);};const photoWrap=document.createElement('div');photoWrap.className='roll-photo-image';photoWrap.append(image,shot.meta,reviewEye());photoButton.append(photoWrap,shot.title);card.append(photoButton,shot.retry);$('#photos').prepend(card);status('Reviewing…');controls();await shutterDone;if(runEpoch!==epoch)return;openPhoto(shot);void drain();if(shots.length===12)void end();}
async function drain(){if(processing)return;processing=true;const run=epoch;try{for(const shot of shots){if(run!==epoch)return;if(shot.state!=='pending')continue;shot.state='sending';shot.title.textContent='Reviewing…';try{const r=await api('news-photo',{roundId,photoId:shot.id,image:shot.judged,thumb:shot.thumb,custom:shot.custom});if(run!==epoch)return;shot.state='done';shot.result=r;money=r.total;total();shot.meta.textContent=dollars(r.earned);tintPhoto(shot.card,r.earned);photoTitle(shot.title,r);$('#headline').textContent=r.headline;city?.record('photo_result',{photoId:shot.id,...r});shot.card.classList.remove('reviewing');if(currentShot===shot&&$('#sale').open)paintPhoto();else{landPhoto(shot.card);showSlip(r);}if(r.earned)moneySound();}catch(e){if(run!==epoch)return;shot.state='failed';shot.card.classList.replace('reviewing','failed');shot.title.textContent='Couldn’t review this photo';shot.retry.hidden=false;shot.error=e.message;if(currentShot===shot)paintPhoto();status(e.message);}}}finally{if(run===epoch){processing=false;if(shots.some(s=>s.state==='pending'))void drain();else maybeFinished();}}}
// A price that lands while the player is back in the city: pulse the card, bump earnings, show a short slip.
let slipTimer=0;
function landPhoto(card){card.classList.remove('landed');void card.offsetWidth;card.classList.add('landed');const n=$('#money');n.classList.remove('money-bump');void n.offsetWidth;n.classList.add('money-bump');}
function showSlip(r){const slip=$('#price-slip');slip.querySelector('h4').textContent=r.headline;slip.querySelector('strong').textContent=r.earned?'+'+dollars(r.earned):'No sale';slip.classList.remove('show');void slip.offsetWidth;slip.classList.add('show');clearTimeout(slipTimer);slipTimer=setTimeout(()=>slip.classList.remove('show'),4000);}
function openPhoto(shot){currentShot=shot;fadeFeedVolume(DIALOG_VOLUME);$('#sale-image').src=shot.image;paintPhoto();if(!$('#sale').open)$('#sale').showModal();}
function paintPhoto(){const shot=currentShot;if(!shot)return;const pending=shot.state==='pending'||shot.state==='sending',r=shot.result;$('#sale').classList.toggle('reviewing',pending);photoTitle($('#sale-headline'),r,pending?'Reviewing…':'Couldn’t review this photo');$('#sale-tag').textContent=pending?'PHOTO TAKEN':r?(r.earned?'PHOTO SOLD':'NO SALE THIS TIME'):'SEND FAILED';if(r){tintPhoto($('#sale'),r.earned);countMoney($('#sale-price'),r.earned);}else $('#sale-price').textContent='';$('#sale-paid').hidden=!r;$('#sale-count').textContent='Photo '+(shots.indexOf(shot)+1)+' of 12';$('#sale-note').hidden=shot.state!=='failed';$('#sale-note').textContent=r?r.reason:'Your shot is saved. Retry without using another photo.';$('#retry-photo').hidden=shot.state!=='failed';}
function retryShot(shot){shot.state='pending';shot.error=null;shot.retry.hidden=true;shot.card.classList.replace('failed','reviewing');shot.title.textContent='Reviewing…';openPhoto(shot);void drain();}
$('#retry-photo').onclick=()=>{if(currentShot?.state==='failed')retryShot(currentShot);};
function dismiss(){if(!$('#sale').open)return;$('#sale').close();currentShot=null;video.muted=!sound;fadeFeedVolume(LIVE_VOLUME);status('Find your next shot.');controls();maybeFinished();}

function maybeFinished(){if(!ending||processing||shots.some(s=>s.state==='pending'||s.state==='sending')||queue.length||$('#sale').open||$('#photo-detail').open||phase==='closing')return;const failed=shots.filter(s=>s.state==='failed').length;$('#final-count').textContent=`${shots.length} photo${shots.length===1?'':'s'} taken${failed?` · ${failed} unscored`:''}`;if($('#result').open)return;renderGallery($('#recap-gallery'),shots,inspectPhoto);$('#download-recap').disabled=!shots.length;$('#recap-status').textContent=shots.length?'':'No photos this round.';if(!$('#result').open){$('#result').showModal();revealRecap($('#result'),money);}}
async function end(){if(ending)return;clearTimeout(retryTimer);retryTimer=0;ending=true;stopLoadingSound();fadeFeedVolume(0);phase='closing';controls();status('Finishing the round…');try{await city?.close();}catch(e){status('Session cleanup failed: '+e.message);}phase='ended';controls();maybeFinished();}
$('#dismiss-sale').onclick=$('#close-review').onclick=()=>void dismiss();$('#sale').addEventListener('cancel',e=>{e.preventDefault();void dismiss();});$('#begin').onclick=()=>{if(sound)context();void start();};$('#welcome').addEventListener('cancel',e=>e.preventDefault());$('#retry-connect').onclick=()=>void start();$('#release').onclick=async()=>{try{await api('stop-sessions');$('#release').hidden=true;status('Previous session stopped. Try again.');$('#connection-title').textContent='All clear. Try again.';}catch(e){status(e.message);}};$('#restart').onclick=()=>void start();$('#again').onclick=()=>{$('#result').close();if(shots.some(s=>s.state==='failed')){status('Retry failed photos from your camera roll, or press Start new round.');$('#restart').hidden=false;}else void start();};$('#sound').onclick=()=>{sound=!sound;setSound(sound);video.muted=!sound;$('#sound').textContent=sound?'SOUND ON':'SOUND OFF';$('#sound').setAttribute('aria-pressed',String(sound));if(sound){context();if(phase==='starting')startLoadingSound();}};window.addEventListener('pagehide',()=>{clearTimeout(retryTimer);stopLoadingSound();city?.unload();});setInterval(()=>{controls();if(phase==='live'&&!ending&&!left())void end();},200);document.querySelectorAll('dialog').forEach(installDialogMotion);$('#sale').addEventListener('close',()=>{controls();maybeFinished();});$('#sale .review-row').prepend(reviewEye());renderOptions();{/* Welcome opens non-modal so the masthead links stay usable; the rest of the game is locked until it closes. */const welcome=$('#welcome'),locked=[...$('#game').children].filter(n=>n!==welcome&&!n.matches('.masthead'));welcome.addEventListener('close',()=>locked.forEach(n=>n.inert=false),{once:true});locked.forEach(n=>n.inert=true);welcome.show();}controls();

let detailIndex=0;
function inspectPhoto(shot){detailIndex=shots.indexOf(shot);if(phase==='live')fadeFeedVolume(DIALOG_VOLUME);$('#detail-image').src=shot.image;$('#detail-title').textContent=shot.result?.headline||'Not scored';$('#detail-download').disabled=!shot.result;detailsFor($('#detail-content'),shot.result);$('#detail-count').textContent=(detailIndex+1)+' of '+shots.length;$('#detail-prev').disabled=detailIndex<=0;$('#detail-next').disabled=detailIndex>=shots.length-1;if(!$('#photo-detail').open)$('#photo-detail').showModal();controls();}
$('#detail-prev').onclick=()=>{if(detailIndex>0)inspectPhoto(shots[detailIndex-1]);};
$('#detail-next').onclick=()=>{if(detailIndex<shots.length-1)inspectPhoto(shots[detailIndex+1]);};
$('#detail-close').onclick=()=>$('#photo-detail').close();
$('#photo-detail').addEventListener('close',()=>{if(phase==='live'&&!$('#sale').open)fadeFeedVolume(LIVE_VOLUME);controls();maybeFinished();});
function saveBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
// Get the front page: the photo laid out under its headline with the price stamp (newsworthy-keepsake.js).
$('#detail-download').onclick=async()=>{const shot=shots[detailIndex],button=$('#detail-download');if(!shot?.result)return;button.disabled=true;const label=button.textContent;button.textContent='Printing…';try{saveBlob(await createFrontPage(shot,detailIndex,shots.length),'newsworthy-front-page-'+(detailIndex+1)+'.png');}catch(e){console.error(e);button.textContent='Try again';setTimeout(()=>{button.textContent=label;},2000);return;}finally{button.disabled=false;}button.textContent=label;};
$('#download-recap').onclick=async()=>{const button=$('#download-recap');button.disabled=true;$('#recap-status').textContent='Making your photo package…';try{saveBlob(await createPhotoPackage(shots,money),'newsworthy-photo-package-'+new Date().toISOString().slice(0,10)+'.png');$('#recap-status').textContent='Photo package saved. Check your downloads.';}catch(e){$('#recap-status').textContent=e.message;}finally{button.disabled=false;}};


// Reading credits must not trigger a photograph.
const credits = document.querySelector('.sound-credits');
credits?.addEventListener('click', event => event.stopPropagation());
credits?.addEventListener('keydown', event => event.stopPropagation());

const ticker = document.querySelector('.ticker');
const tickerPause = document.querySelector('.ticker-pause');
ticker.addEventListener('click', event => event.stopPropagation());
ticker.addEventListener('keydown', event => event.stopPropagation());
tickerPause.onclick = () => {
  const paused = ticker.classList.toggle('ticker-paused');
  tickerPause.setAttribute('aria-pressed', String(paused));
  tickerPause.setAttribute('aria-label', paused ? 'Resume scrolling text' : 'Pause scrolling text');
  tickerPause.textContent = paused ? '▶' : 'Ⅱ';
};

$('#how-it-works').onclick=()=>$('#about').showModal();
$('#high-scores').onclick=()=>$('#scores-dialog').showModal();
