import {installDialogMotion,shutter,revealRecap} from './newsworthy-motion.js';
import {addEventHistory,resetEventHistory} from './newsworthy-event-history.js';
import {dollars,tintPhoto,photoTitle,countMoney,detailsFor} from './newsworthy-photo-ui.js';
import {renderGallery,createRecap} from './newsworthy-recap.js';
import {LiveCity,api} from './newsworthy-stream.js';
import {EVENTS,EVENT_WINDOW_MS,CAMERA} from './newsworthy-events.js';
import {cropRect} from './newsworthy-crop.js';
import {context,setSound,shutterSound,moneySound,startLoadingSound,stopLoadingSound} from './newsworthy-sounds.js';
import {playIntro,VIEWFINDER_BEATS} from './newsworthy-intro.js';
const $=s=>document.querySelector(s),video=$('#feed'),empty=$('#photos').innerHTML;
const LIVE_VOLUME=.5,DIALOG_VOLUME=.08,VOLUME_FADE_MS=400;
let volumeFade;
function fadeFeedVolume(target,duration=VOLUME_FADE_MS){cancelAnimationFrame(volumeFade);const from=video.volume;if(!duration){video.volume=target;return;}const started=performance.now();const tick=now=>{const progress=Math.min(1,(now-started)/duration),eased=1-Math.pow(1-progress,3);video.volume=from+(target-from)*eased;if(progress<1)volumeFade=requestAnimationFrame(tick);};volumeFade=requestAnimationFrame(tick);}
fadeFeedVolume(LIVE_VOLUME,0);
let city,roundId,phase='idle',shots=[],money=0,deadline=0,pausedAt=0,cooling=0,sending=false,sound=true,epoch=0,processing=false,queue=[],ending=false,photoReadyAt=0,currentShot=null,retryTimer=0;
let intro,lastIncident=null,aimX=.5,aimY=.45,eventTurn=0,playing=false;
function renderOptions(){const box=$('#event-options');box.replaceChildren();for(const [index,event] of EVENTS.entries()){const button=document.createElement('button');button.dataset.event=event.id;const code=document.createElement('span');code.className='event-icon';code.textContent=event.code;const number=document.createElement('span');number.className='event-number';number.textContent=String(index+1).padStart(2,'0');const label=document.createElement('span');label.className='event-label';label.textContent=event.label;button.append(code,number,label);button.onclick=()=>void send(event.prompt+' '+CAMERA,event.label);box.append(button);}}
function refreshEvents(){if(playing&&!sending&&Date.now()>=cooling){playing=false;eventTurn++;renderOptions();}$('#event-options').hidden=false;$('#event-playing').hidden=!playing;}
const broadcast=$('.picture-stage');
function aim(){const r=broadcast.getBoundingClientRect();const crop=cropRect(video.videoWidth||1280,video.videoHeight||720,r.width,r.height,aimX,aimY,.48,'contain');Object.assign($('#aim').style,{left:crop.left+'px',top:crop.top+'px',width:crop.width+'px',height:crop.height+'px'});return crop;}
broadcast.addEventListener('pointermove',e=>{if(e.target.closest('button,dialog'))return;const r=broadcast.getBoundingClientRect();aimX=(e.clientX-r.left)/r.width;aimY=(e.clientY-r.top)/r.height;aim();});
broadcast.addEventListener('click',e=>{if(e.target.closest('button,dialog,#connection,.on-air,.stats'))return;const r=broadcast.getBoundingClientRect();aimX=(e.clientX-r.left)/r.width;aimY=(e.clientY-r.top)/r.height;aim();capture();});
new ResizeObserver(()=>aim()).observe(broadcast);video.addEventListener('loadedmetadata',aim);video.addEventListener('resize',aim);
function status(t){$('#notice').textContent=t;$('#notice').classList.toggle('incoming',t.startsWith('Incoming:'));}
function total(){['money','total','final-total'].forEach(id=>$('#'+id).textContent='$'+money.toLocaleString());}
function left(){return deadline?Math.max(0,Math.ceil((deadline-Date.now())/1000)):120;}
function controls(){const active=phase==='live'&&!ending&&!$('#sale').open&&!$('#photo-detail').open;const photoWait=Math.max(0,(photoReadyAt-Date.now())/1000);$('#aim .shoot-hint').hidden=shots.length>0;$('#aim').classList.toggle('low-shots',shots.length>=9);$('#aim').classList.toggle('cooling',photoWait>0);refreshEvents();document.querySelectorAll('[data-event]').forEach(b=>{b.disabled=!active||sending||playing;b.classList.toggle('event-cooling',playing);b.style.setProperty('--cooldown-fill',(sending?1:Math.max(0,Math.min(1,(cooling-Date.now())/EVENT_WINDOW_MS)))*100+'%');});$('#custom button').disabled=!active||sending;$('#idea').disabled=!active;$('#remaining').textContent=12-shots.length;$('#shots-label').textContent=shots.length===11?' SHOT LEFT':' SHOTS LEFT';$('#count').textContent=shots.length+' / 12';const s=left();$('#clock').textContent=Math.floor(s/60)+':'+String(s%60).padStart(2,'0');$('#cooldown').textContent=sending?'Sending…':`More in ${Math.max(0,Math.ceil((cooling-Date.now())/1000))}s`;$('#restart').disabled=phase==='starting'||phase==='closing';}
async function start(){if(['starting','closing','live'].includes(phase))return;clearTimeout(retryTimer);retryTimer=0;const run=++epoch;phase='starting';fadeFeedVolume(LIVE_VOLUME,0);$('#restart').textContent='END ROUND';$('#restart').onclick=()=>void end();ending=false;shots=[];currentShot=null;$('#sale').close();money=0;photoReadyAt=0;deadline=0;pausedAt=0;queue=[];processing=false;cooling=0;sending=false;roundId=null;eventTurn=0;playing=false;renderOptions();lastIncident=null;resetEventHistory();total();$('#photos').innerHTML=empty;$('#welcome').close();$('#result').close();intro?.stop();const opening=intro=playIntro($('#connection'),{beats:VIEWFINDER_BEATS});$('#connection-note').hidden=true;$('#retry-connect').hidden=true;$('#release').hidden=true;$('#opening-scene').hidden=false;video.muted=!sound;void video.play().catch(()=>{});startLoadingSound();controls();try{roundId=(await api('news-round')).roundId;const instance=city=new LiveCity(video,status,e=>{if(run!==epoch)return;status(e.message);if(phase==='live')void end();});await Promise.all([instance.start(),opening.ready]);if(run!==epoch||instance.closed)return;stopLoadingSound();$('#opening-scene').hidden=true;opening.live();phase='live';deadline=Date.now()+120000;status('You’re live. Find a story and get the shot.');controls();}catch(e){if(run!==epoch)return;opening.stop();stopLoadingSound();console.warn('Live start failed',e);await city?.close().catch(()=>{});phase='error';const message=String(e?.message||e),busy=/quota_exceeded|concurrent_sessions_per_model/.test(message);status(busy?'Previous live session is still closing. Retrying automatically…':message);$('#connection-title').textContent=busy?'Almost there.':'Couldn’t reach the city.';$('#connection-note').textContent=busy?'Trying again in 10 seconds.':'Your round hasn’t started. Try again in a moment.';$('#connection-note').hidden=false;$('#retry-connect').hidden=false;$('#release').hidden=!message.includes('session is still open');if(busy)retryTimer=setTimeout(()=>{retryTimer=0;if(run===epoch&&phase==='error')void start();},10000);controls();}}
async function send(prompt,label,custom=false){if(phase!=='live'||ending||sending||(!custom&&playing)||$('#sale').open)return;sending=true;playing=true;$('#event-name').textContent=label;lastIncident={label,clicked:Date.now(),activeElapsed:0};city.record('incident_clicked',{label});controls();status('Sending: '+label);try{await city.command('set_prompt',{prompt,passthrough:false});lastIncident.accepted=Date.now();addEventHistory(label,120-left());const incoming='Incoming: '+label;status(incoming);setTimeout(()=>{if($('#notice').textContent===incoming)status('Sent: '+label);},5000);}catch(e){status('Prompt not confirmed: '+e.message);}finally{sending=false;cooling=Date.now()+EVENT_WINDOW_MS;controls();}}
$('#custom').onsubmit=e=>{e.preventDefault();const text=$('#idea').value.trim();if(text&&phase==='live'&&!ending&&!sending&&!$('#sale').open){void send(text+' '+CAMERA,text,true);$('#idea').value='';}};
async function capture(){if(phase!=='live'||ending||shots.length>=12||($('#sale').open||$('#photo-detail').open)||!left()||video.readyState<2||Date.now()<photoReadyAt)return;const runEpoch=epoch;const c=document.createElement('canvas');const crop=aim();c.width=Math.min(960,Math.round(crop.sw));c.height=Math.round(c.width*3/4);c.getContext('2d').drawImage(video,crop.sx,crop.sy,crop.sw,crop.sh,0,0,c.width,c.height);const shot={id:'shot-'+(shots.length+1),image:c.toDataURL('image/jpeg',.82),state:'pending'};shots.push(shot);photoReadyAt=Date.now()+2000;city.record('photo_captured',{photoId:shot.id});shutterSound();const shutterDone=shutter($('#flash'));$('#photos .empty')?.remove();const card=document.createElement('article');card.className='photo';shot.card=card;const image=new Image();image.src=shot.image;image.alt='Your photo '+shots.length;shot.meta=document.createElement('div');shot.meta.className='photo-meta';shot.title=document.createElement('h3');shot.title.textContent='Reviewing…';shot.retry=document.createElement('button');shot.retry.className='retry-photo';shot.retry.textContent='RETRY PHOTO';shot.retry.hidden=true;shot.retry.onclick=()=>retryShot(shot);const photoButton=document.createElement('button');photoButton.className='roll-photo-button';photoButton.setAttribute('aria-label','View photo '+shots.length);photoButton.onclick=()=>{if(shot.result)inspectPhoto(shot);};const photoWrap=document.createElement('div');photoWrap.className='roll-photo-image';photoWrap.append(image,shot.meta);photoButton.append(photoWrap,shot.title);card.append(photoButton,shot.retry);$('#photos').prepend(card);status('Reviewing…');controls();await shutterDone;if(runEpoch!==epoch)return;openPhoto(shot);void drain();if(shots.length===12)void end();}
async function drain(){if(processing)return;processing=true;const run=epoch;try{for(const shot of shots){if(run!==epoch)return;if(shot.state!=='pending')continue;shot.state='sending';shot.title.textContent='Reviewing…';try{const r=await api('news-photo',{roundId,photoId:shot.id,image:shot.image});if(run!==epoch)return;shot.state='done';shot.result=r;money=r.total;total();shot.meta.textContent=dollars(r.earned);tintPhoto(shot.card,r.earned);photoTitle(shot.title,r);$('#headline').textContent=r.headline;city?.record('photo_result',{photoId:shot.id,...r});if(currentShot===shot)paintPhoto();if(r.earned)moneySound();}catch(e){if(run!==epoch)return;shot.state='failed';shot.title.textContent='Editor unavailable. Retry this photo.';shot.retry.hidden=false;shot.error=e.message;if(currentShot===shot)paintPhoto();status(e.message);}}}finally{if(run===epoch){processing=false;if(shots.some(s=>s.state==='pending'))void drain();else maybeFinished();}}}
function openPhoto(shot){currentShot=shot;fadeFeedVolume(DIALOG_VOLUME);$('#sale-image').src=shot.image;paintPhoto();if(!$('#sale').open)$('#sale').showModal();}
function paintPhoto(){const shot=currentShot;if(!shot)return;const pending=shot.state==='pending'||shot.state==='sending',r=shot.result;$('#sale').classList.toggle('pending-photo',pending);photoTitle($('#sale-headline'),r,pending?'Reviewing…':'Editor unavailable');$('#sale-tag').textContent=pending?'PHOTO CAPTURED':r?(r.earned?'PHOTO SOLD':'NO SALE THIS TIME'):'SEND FAILED';if(r){tintPhoto($('#sale'),r.earned);countMoney($('#sale-price'),r.earned);}else $('#sale-price').textContent='';$('#sale-paid').hidden=!r;$('#sale-count').textContent='Photo '+(shots.indexOf(shot)+1)+' of 12';$('#sale-note').hidden=shot.state!=='failed';$('#sale-note').textContent=pending?'Hold for your headline.':r?r.reason:'Your shot is saved. Retry without using another photo.';$('#dismiss-sale').disabled=pending;$('#dismiss-sale').textContent=pending?'WAITING FOR EDITOR…':'BACK TO THE CITY →';$('#retry-photo').hidden=shot.state!=='failed';}
function retryShot(shot){shot.state='pending';shot.error=null;shot.retry.hidden=true;openPhoto(shot);void drain();}
$('#retry-photo').onclick=()=>{if(currentShot?.state==='failed')retryShot(currentShot);};
function dismiss(){if(!$('#sale').open||['pending','sending'].includes(currentShot?.state))return;$('#sale').close();currentShot=null;video.muted=!sound;fadeFeedVolume(LIVE_VOLUME);status('Find your next shot.');controls();maybeFinished();}

function maybeFinished(){if(!ending||processing||shots.some(s=>s.state==='pending'||s.state==='sending')||queue.length||$('#sale').open||$('#photo-detail').open||phase==='closing')return;const failed=shots.filter(s=>s.state==='failed').length;$('#final-count').textContent=`${shots.length} photos${failed?` · ${failed} unscored`:''}`;if($('#result').open)return;renderGallery($('#recap-gallery'),shots,inspectPhoto);$('#download-recap').disabled=!shots.length;$('#recap-status').textContent=shots.length?'':'No photos this round.';if(!$('#result').open){$('#result').showModal();revealRecap($('#result'),money);}}
async function end(){if(ending)return;clearTimeout(retryTimer);retryTimer=0;ending=true;stopLoadingSound();fadeFeedVolume(0);phase='closing';controls();status('Finishing the round…');try{await city?.close();}catch(e){status('Session cleanup failed: '+e.message);}phase='ended';controls();maybeFinished();}
$('#dismiss-sale').onclick=()=>void dismiss();$('#sale').addEventListener('cancel',e=>{e.preventDefault();void dismiss();});$('#begin').onclick=()=>{if(sound)context();void start();};$('#welcome').addEventListener('cancel',e=>e.preventDefault());$('#retry-connect').onclick=()=>void start();$('#release').onclick=async()=>{try{await api('stop-sessions');$('#release').hidden=true;status('Previous session stopped. Try again.');$('#connection-title').textContent='All clear. Try again.';}catch(e){status(e.message);}};$('#restart').onclick=()=>void end();$('#again').onclick=()=>{$('#result').close();if(shots.some(s=>s.state==='failed')){status('Retry failed photos from your camera roll, or press Start new round.');$('#restart').textContent='START NEW ROUND';$('#restart').onclick=()=>void start();}else void start();};$('#sound').onclick=()=>{sound=!sound;setSound(sound);video.muted=!sound;$('#sound').textContent=sound?'SOUND ON':'SOUND OFF';$('#sound').setAttribute('aria-pressed',String(sound));if(sound){context();if(phase==='starting')startLoadingSound();}};window.addEventListener('pagehide',()=>{clearTimeout(retryTimer);stopLoadingSound();city?.unload();});setInterval(()=>{controls();if(phase==='live'&&!ending&&!left())void end();},200);document.querySelectorAll('dialog').forEach(installDialogMotion);$('#sale').addEventListener('close',()=>{controls();maybeFinished();});renderOptions();$('#welcome').showModal();controls();

let detailIndex=0;
function inspectPhoto(shot){detailIndex=shots.indexOf(shot);if(phase==='live')fadeFeedVolume(DIALOG_VOLUME);$('#detail-image').src=shot.image;photoTitle($('#detail-title'),shot.result);detailsFor($('#detail-content'),shot.result);$('#detail-count').textContent=(detailIndex+1)+' of '+shots.length;$('#detail-prev').disabled=detailIndex<=0;$('#detail-next').disabled=detailIndex>=shots.length-1;if(!$('#photo-detail').open)$('#photo-detail').showModal();controls();}
$('#detail-prev').onclick=()=>{if(detailIndex>0)inspectPhoto(shots[detailIndex-1]);};
$('#detail-next').onclick=()=>{if(detailIndex<shots.length-1)inspectPhoto(shots[detailIndex+1]);};
$('#detail-close').onclick=()=>$('#photo-detail').close();
$('#photo-detail').addEventListener('close',()=>{if(phase==='live'&&!$('#sale').open)fadeFeedVolume(LIVE_VOLUME);controls();maybeFinished();});
$('#download-recap').onclick=async()=>{const button=$('#download-recap');button.disabled=true;$('#recap-status').textContent='Making your recap…';try{const blob=await createRecap(shots,money),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='newsworthy-'+new Date().toISOString().slice(0,10)+'.png';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);$('#recap-status').textContent='Recap ready. Check your downloads.';}catch(e){$('#recap-status').textContent=e.message;}finally{button.disabled=false;}};


// Reading credits must not trigger a photograph.
const credits = document.querySelector('.sound-credits');
credits?.addEventListener('click', event => event.stopPropagation());
credits?.addEventListener('keydown', event => event.stopPropagation());

const ticker = document.querySelector('.ticker');
const tickerPause = document.querySelector('.ticker-pause');
ticker.addEventListener('click', event => event.stopPropagation());
ticker.addEventListener('keydown', event => event.stopPropagation());
tickerPause.onclick = () => {
  const paused = ticker.classList.toggle('ticker-paused');
  tickerPause.setAttribute('aria-pressed', String(paused));
  tickerPause.setAttribute('aria-label', paused ? 'Resume scrolling text' : 'Pause scrolling text');
  tickerPause.textContent = paused ? '▶' : 'Ⅱ';
};

// Header help reuses the existing instructions without starting another round.
const help=document.createElement('dialog');help.id='help-dialog';help.className='np np-wide';help.setAttribute('aria-label','How to play');
help.append($('#welcome .sheet').cloneNode(true));help.querySelectorAll('[id]').forEach(node=>node.removeAttribute('id'));
const closeHelp=help.querySelector('.np-btn');closeHelp.textContent='Back to the city';closeHelp.onclick=()=>help.close();document.body.append(help);installDialogMotion(help);
$('#how-to-play').onclick=()=>help.showModal();
$('#high-scores').onclick=()=>$('#scores-dialog').showModal();
