import test from 'node:test';import assert from 'node:assert/strict';import {createNewsJudge,priceFor} from './news-judge-api.js';
const image=n=>'data:image/jpeg;base64,'+Buffer.from('photo'+n).toString('base64');
const verdict=(previous_index=-1,clarity=4)=>({event_type:'fire',event_strength:2,clarity,spectacle:2,headline:'Visible fire',reason:'Fire visible',previous_index});
test('ordinary earns zero; continuous score determines price',()=>{assert.equal(priceFor({event_strength:0,clarity:4,spectacle:4}),0);assert.equal(priceFor(verdict()),500);});
test('idempotent retries, half-price repeats, full-price new subjects in same category',async()=>{let calls=0;const answers=[verdict(-1,2),verdict(0,4),verdict(-1,4)];const j=createNewsJudge('test',async()=>({ok:true,json:async()=>({choices:[{message:{content:JSON.stringify(answers[calls++])}}]})}));const {roundId}=j.create();const input={roundId,photoId:'shot-1',image:image(1)};const [a,b]=await Promise.all([j.judge(input),j.judge(input)]);assert.equal(a.earned,250);assert.deepEqual(a,b);assert.equal(calls,1);const dup=await j.judge({...input,photoId:'shot-2'});assert.equal(dup.earned,125);assert.equal(calls,1);const improved=await j.judge({...input,photoId:'shot-3',image:image(3)});assert.equal(improved.earned,250);assert.equal(improved.total,625);const same=await j.judge({...input,photoId:'shot-4',image:image(4)});assert.equal(same.earned,500);assert.equal(same.total,1125);});
test('failed judge can retry same photo without a zero payout',async()=>{let n=0;const j=createNewsJudge('test',async()=>{if(n++<2)throw new Error('offline');return {ok:true,json:async()=>({choices:[{message:{content:JSON.stringify(verdict())}}]})};});const {roundId}=j.create(),x={roundId,photoId:'shot-1',image:image(1)};await assert.rejects(j.judge(x),/offline/);assert.equal((await j.judge(x)).earned,500);});
test('judge calls Gemini directly with bearer authentication',async()=>{let called=false;const j=createNewsJudge('test-key',async(url,init)=>{called=true;assert.equal(url,'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions');assert.equal(init.headers.Authorization,'Bearer test-key');assert.equal(JSON.parse(init.body).model,'gemini-3.5-flash-lite');return {ok:true,json:async()=>({choices:[{message:{content:JSON.stringify(verdict())}}]})};});const {roundId}=j.create();await j.judge({roundId,photoId:'shot-1',image:image(1)});assert.equal(called,true);});
test('round limits and malformed input',async()=>{const j=createNewsJudge('test',async()=>({ok:true,json:async()=>({choices:[{message:{content:JSON.stringify(verdict())}}]})}));const {roundId}=j.create();await assert.rejects(j.judge({roundId,photoId:'shot-1',image:'https://example.com'}));for(let n=1;n<=12;n++)await j.judge({roundId,photoId:`shot-${n}`,image:image(n)});await assert.rejects(j.judge({roundId,photoId:'shot-13',image:image(13)}),/12 photos/);});

test('repeat score and payout agree, including fractional ratings',async()=>{const v={...verdict(),event_strength:3,spectacle:4,clarity:3};const j=createNewsJudge('test',async()=>({ok:true,json:async()=>({choices:[{message:{content:JSON.stringify(v)}}]})}));const {roundId}=j.create();const first=await j.judge({roundId,photoId:'shot-1',image:image(1)});const repeat=await j.judge({roundId,photoId:'shot-2',image:image(1)});assert.equal(first.score,6.56);assert.equal(first.earned,656);assert.equal(repeat.score,3.28);assert.equal(repeat.earned,328);});

const reply=v=>({ok:true,json:async()=>({choices:[{message:{content:JSON.stringify(v)}}]})});
const sse=text=>({ok:true,headers:new Headers({'content-type':'text/event-stream'}),body:(async function*(){const e=new TextEncoder();yield e.encode(': OPENROUTER PROCESSING\n\n');for(let i=0;i<text.length;i+=7)yield e.encode(`data: ${JSON.stringify({choices:[{delta:{content:text.slice(i,i+7)}}]})}\n\n`);yield e.encode('data: [DONE]\n\n');})()});
const later=(ms,signal,value)=>new Promise((resolve,reject)=>{const t=setTimeout(()=>resolve(value),ms);signal?.addEventListener('abort',()=>{clearTimeout(t);reject(new DOMException('aborted','AbortError'));});});
test('streamed replies are reassembled across chunks',async()=>{let body;const j=createNewsJudge('test',async(url,init)=>{body=JSON.parse(init.body);return sse(JSON.stringify(verdict()));});const {roundId}=j.create();const r=await j.judge({roundId,photoId:'shot-1',image:image(1)});assert.equal(body.stream,true);assert.equal(r.earned,500);assert.equal(r.attempt,1);});
test('slow first request: backup is sent and the first valid answer wins',async()=>{const signals=[];const j=createNewsJudge('test',async(url,init)=>{signals.push(init.signal);return signals.length===1?later(500,init.signal,reply(verdict())):reply({...verdict(),headline:'Backup'});},{backupAfter:20});const {roundId}=j.create();const r=await j.judge({roundId,photoId:'shot-1',image:image(1)});assert.equal(signals.length,2);assert.equal(r.attempt,2);assert.equal(r.headline,'Backup');assert.equal(signals[0].aborted,true);});
test('fast answer never sends a backup',async()=>{let calls=0;const j=createNewsJudge('test',async()=>{calls++;return reply(verdict());},{backupAfter:20});const {roundId}=j.create();await j.judge({roundId,photoId:'shot-1',image:image(1)});await new Promise(r=>setTimeout(r,40));assert.equal(calls,1);});
test('unreadable reply retries straight away instead of failing the photo',async()=>{let calls=0;const j=createNewsJudge('test',async()=>++calls===1?sse('{"event_type":"fi'):reply(verdict()));const {roundId}=j.create();const r=await j.judge({roundId,photoId:'shot-1',image:image(1)});assert.equal(calls,2);assert.equal(r.attempt,2);});
test('two failed attempts surface the error',async()=>{let calls=0;const j=createNewsJudge('test',async()=>{calls++;return {ok:false,status:503};});const {roundId}=j.create();await assert.rejects(j.judge({roundId,photoId:'shot-1',image:image(1)}),/Editor unavailable \(503\)/);assert.equal(calls,2);});
test('earlier photos are sent back as thumbnails',async()=>{const sent=[];const j=createNewsJudge('test',async(url,init)=>{sent.push(JSON.parse(init.body).messages[1].content.filter(c=>c.type==='image_url').map(c=>c.image_url.url));return reply(verdict());});const {roundId}=j.create();await j.judge({roundId,photoId:'shot-1',image:image(1),thumb:image('t1')});await j.judge({roundId,photoId:'shot-2',image:image(2),thumb:image('t2')});assert.deepEqual(sent[1],[image('t1'),image(2)]);await assert.rejects(j.judge({roundId,photoId:'shot-3',image:image(3),thumb:'https://example.com'}),/Invalid photograph/);});
