import test from 'node:test';import assert from 'node:assert/strict';import {createNewsJudge,priceFor} from './news-judge-api.js';
const image=n=>'data:image/jpeg;base64,'+Buffer.from('photo'+n).toString('base64');
const verdict=(previous_index=-1,clarity=4)=>({event_type:'fire',event_strength:2,clarity,spectacle:2,headline:'Visible fire',reason:'Fire visible',previous_index});
test('ordinary earns zero; continuous score determines price',()=>{assert.equal(priceFor({event_strength:0,clarity:4,spectacle:4}),0);assert.equal(priceFor(verdict()),500);});
test('idempotent retries, half-price repeats, full-price new subjects in same category',async()=>{let calls=0;const answers=[verdict(-1,2),verdict(0,4),verdict(-1,4)];const j=createNewsJudge('test',async()=>({ok:true,json:async()=>({choices:[{message:{content:JSON.stringify(answers[calls++])}}]})}));const {roundId}=j.create();const input={roundId,photoId:'shot-1',image:image(1)};const [a,b]=await Promise.all([j.judge(input),j.judge(input)]);assert.equal(a.earned,250);assert.deepEqual(a,b);assert.equal(calls,1);const dup=await j.judge({...input,photoId:'shot-2'});assert.equal(dup.earned,125);assert.equal(calls,1);const improved=await j.judge({...input,photoId:'shot-3',image:image(3)});assert.equal(improved.earned,250);assert.equal(improved.total,625);const same=await j.judge({...input,photoId:'shot-4',image:image(4)});assert.equal(same.earned,500);assert.equal(same.total,1125);});
test('failed judge can retry same photo without a zero payout',async()=>{let n=0;const j=createNewsJudge('test',async()=>{if(!n++)throw new Error('offline');return {ok:true,json:async()=>({choices:[{message:{content:JSON.stringify(verdict())}}]})};});const {roundId}=j.create(),x={roundId,photoId:'shot-1',image:image(1)};await assert.rejects(j.judge(x),/offline/);assert.equal((await j.judge(x)).earned,500);});
test('round limits and malformed input',async()=>{const j=createNewsJudge('test',async()=>({ok:true,json:async()=>({choices:[{message:{content:JSON.stringify(verdict())}}]})}));const {roundId}=j.create();await assert.rejects(j.judge({roundId,photoId:'shot-1',image:'https://example.com'}));for(let n=1;n<=12;n++)await j.judge({roundId,photoId:`shot-${n}`,image:image(n)});await assert.rejects(j.judge({roundId,photoId:'shot-13',image:image(13)}),/12 photos/);});

test('repeat score and payout agree, including fractional ratings',async()=>{const v={...verdict(),event_strength:3,spectacle:4,clarity:3};const j=createNewsJudge('test',async()=>({ok:true,json:async()=>({choices:[{message:{content:JSON.stringify(v)}}]})}));const {roundId}=j.create();const first=await j.judge({roundId,photoId:'shot-1',image:image(1)});const repeat=await j.judge({roundId,photoId:'shot-2',image:image(1)});assert.equal(first.score,6.56);assert.equal(first.earned,656);assert.equal(repeat.score,3.28);assert.equal(repeat.earned,328);});
